name: 'Setup Git'
description: 'Install a specific version of Git from source'

inputs:
  version:
    description: 'Git version to install (e.g., 2.40.0)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install build dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-gnutls-dev libexpat1-dev gettext libz-dev libssl-dev

    - name: Build and install git ${{ inputs.version }}
      shell: bash
      run: |
        cd /tmp
        curl -L "https://github.com/git/git/archive/refs/tags/v${{ inputs.version }}.tar.gz" | tar xz
        cd "git-${{ inputs.version }}"
        make prefix=/usr/local all -j$(nproc)
        sudo make prefix=/usr/local install

    - name: Add to PATH
      shell: bash
      run: echo "/usr/local/bin" >> $GITHUB_PATH

    - name: Verify installation
      shell: bash
      run: |
        INSTALLED=$(/usr/local/bin/git --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
        if [ "$INSTALLED" != "${{ inputs.version }}" ]; then
          echo "ERROR: Expected git ${{ inputs.version }}, got $INSTALLED"
          exit 1
        fi
        echo "Git ${{ inputs.version }} installed successfully"
