/**
 * Generates readable unique IDs like "happy-penguin-x3f".
 *
 * Used for test isolation - each test gets a unique ID that is appended
 * to branch names and commit messages for easy identification.
 */

const adjectives = [
  "happy",
  "swift",
  "brave",
  "calm",
  "eager",
  "fair",
  "glad",
  "keen",
  "wise",
  "bold",
  "warm",
  "cool",
  "neat",
  "pure",
  "safe",
  "bright",
  "quick",
  "sharp",
  "soft",
  "wild",
  "fresh",
  "clear",
  "proud",
  "quiet",
  "vivid",
  "gentle",
  "fierce",
  "clever",
  "steady",
  "golden",
  "silver",
  "cosmic",
  "humble",
  "noble",
  "silent",
  "mighty",
  "tiny",
  "grand",
  "lucky",
  "mellow",
  "zesty",
  "rustic",
  "glossy",
  "fuzzy",
  "crisp",
];

const nouns = [
  "penguin",
  "falcon",
  "tiger",
  "dolphin",
  "eagle",
  "panda",
  "koala",
  "otter",
  "rabbit",
  "badger",
  "fox",
  "owl",
  "bear",
  "wolf",
  "hawk",
  "whale",
  "shark",
  "raven",
  "crane",
  "lynx",
  "moose",
  "bison",
  "zebra",
  "lemur",
  "sloth",
  "gecko",
  "finch",
  "heron",
  "ibis",
  "quail",
  "stork",
  "viper",
  "cobra",
  "manta",
  "squid",
  "crab",
  "seal",
  "mole",
  "deer",
  "elk",
  "wren",
  "swan",
  "dove",
  "lark",
  "newt",
];

export function generateUniqueId(): string {
  const adj = adjectives[Math.floor(Math.random() * adjectives.length)];
  const noun = nouns[Math.floor(Math.random() * nouns.length)];
  // Add a short random suffix to ensure uniqueness even with same word combo
  const suffix = Math.random().toString(36).slice(2, 5);
  return `${adj}-${noun}-${suffix}`;
}
